[versions]
jackson = "2.16.1" # dont touch me, 2.18.3 ist bugged
kotlin = "2.3.0"
junit = "5.8.1"

[plugins]
jpackage = { id = 'org.beryx.runtime', version = '1.12.7' }
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7" }

[libraries]
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
kotlinx-cli = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-cli', version = '0.3.6' }
kotlinx-coroutines = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-coroutines-core', version = '1.10.1' }
lgooddatepicker = { group = 'com.github.lgooddatepicker', name = 'LGoodDatePicker', version = '11.2.1' }
apache-pdfbox = { group = 'org.apache.pdfbox', name = 'pdfbox', version = '2.0.27' }
apache-commonsCSV = { group = "org.apache.commons", name = "commons-csv", version = "1.9.0" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin"  }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
squareup-kotlinpoet = { group = 'com.squareup', name = 'kotlinpoet', version = '1.10.0' }
